# 头部菜单，title: link
menu:
  首页: /
  分类: /categories
  标签: /tags
  归档: /archives
  关于: /about

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐（随机播放）
mp3:
  - http://link.hhtjim.com/163/425570952.mp3
  - http://link.hhtjim.com/163/425570952.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图（随机调用,支持外链）
cover:
  - /img/cover1.jpg
  - /img/cover2.jpg
  - /img/cover3.jpg
  - /img/cover4.jpg
  - /img/cover5.jpg
  - /img/cover6.jpg
  - /img/cover7.jpg
  - /img/cover8.jpg
  - /img/cover9.jpg
  - /img/cover10.jpg
  - /img/cover11.jpg
  - /img/cover12.jpg
  - /img/cover13.jpg
  - /img/cover14.jpg
  - /img/cover15.jpg
  - /img/cover16.jpg
  - /img/cover17.jpg
  - /img/cover18.jpg
  - /img/cover19.jpg
  - /img/cover20.jpg
  - /img/cover21.jpg
  - /img/cover22.jpg
  - /img/cover23.jpg
  - /img/cover24.jpg
  - /img/cover25.jpg
  - /img/cover26.jpg
  - /img/cover27.jpg
  - /img/cover28.jpg
  - /img/cover29.jpg
  - /img/cover30.jpg
  - /img/cover31.jpg
  - /img/cover32.jpg
  - /img/cover33.jpg
  - /img/cover34.jpg
  - /img/cover35.jpg
  - /img/cover36.jpg
  - /img/cover37.jpg
  - /img/cover38.jpg
  - /img/cover39.jpg
  - /img/cover40.jpg
  - /img/cover41.jpg
  - /img/cover42.jpg
  - /img/cover43.jpg
  - /img/cover44.jpg
  - /img/cover45.jpg
  - /img/cover46.jpg
  - /img/cover47.jpg
  - /img/cover48.jpg
  - /img/cover49.jpg
  - /img/cover50.jpg
  - /img/cover51.jpg
  - /img/cover52.jpg
  - /img/cover53.jpg
  - /img/cover54.jpg
  - /img/cover55.jpg
  - /img/cover56.jpg
  - /img/cover57.jpg
  - /img/cover58.jpg
  - /img/cover59.jpg
  - /img/cover60.jpg

# 是否使用mathjax
mathjax: false

# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
  # 是否启用
  enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
  github: https://github.com/AruSeito
  email: mailto:AruSeito@gmail.com

# 备案
beian:
  # 是否显示备案信息
  enable: false
  # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
  enableFooter: false
  # 备案号
  beianInfo: 冀ICP备xxxxxxx号
  # 链接地址
  link: http://www.beian.miit.gov.cn

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否启用评论功能
  enable: false
  # 是否自动展开评论框
  autoExpand: false
  # 应用编号
  clientID: ""
  # 应用秘钥
  clientSecret: ""
  # issue仓库名
  repo: ""
  # Github名
  owner: ""
  # Github名
  admin: [""]
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
